### ISSUE TITLE
Did u handle buy event on this template?

### ISSUE THREAD

**Issue by kithokit** [PredictionIO/template-scala-parallel-ecommercerecommendation#1]
I didn't find anything to handle buy events in DataSource.scala.

To handle this, should we need to use Two algorithm to handle buy and view events separately and combine it at the end?

**Comment by k4hoo** [comment]
By the default, the buy event is used for unseen filtering during serving only (see algorithm's predict()).
Yes. To use buy event in training data, you can
1) use two algorithms and combine like you said.
2) another easier way is to aggregate buy with view event (say +1 for view, +5 for buy) but it may or may not give you good result, depending on your application and nature of data.
see https://groups.google.com/d/msg/predictionio-user/6kcAIoDXgF4/SVVDWImCDQEJ
