### ISSUE TITLE
item related recommendation

### ISSUE THREAD

**Issue by bonbon1702** [PredictionIO/template-scala-parallel-ecommercerecommendation#2]
Is it possible to recommend related item?

i mean, query "item" => "i1" and finding related item?

Thank you!

**Comment by k4hoo** [comment]
Yes. would Similar Product work for your case? Query is a list of item IDs.
http://templates.prediction.io/PredictionIO/template-scala-parallel-similarproduct

**Comment by bonbon1702** [comment]
Thank you, it is helpful. 
now i want to query, user and item
Do you have same hint to modify Algorithm?

**Comment by k4hoo** [comment]
hi @bonbon1702 , would you explain more what you meant by "want to query, user and item" ?
You can deploy multiple engine and share data of same appName and each engine can be used for different purposes

**Comment by bonbon1702** [comment]
thank you for response, i understand your answer, but i dont want deploy multiple engine.
I want in 1 engine, i can query to get recommend by item or user or both. I mean: 
+ query by item 
sendQuery(array('items'=> array('i1'), 'num'=> 4))
+ query by user
sendQuery(array('users'=> array('u1'), 'num'=> 4))
+ or both 
sendQuery(array('items'=> array('i1'),'users'=> array('u1'), 'num'=> 4))

**Comment by k4hoo** [comment]
I see. It's possible. What's the reason that you prefer handling different use cases in one engine rather than deploying separated engines?
One of the advantages of deploying different engines is that you can easily change/modify engine for that particular use case without affecting others.
For cases like sendQuery(array('items'=> array('i1'),'users'=> array('u1'), 'num'=> 4)), do you expect to return 4 items similar to i1 and also another 4 items recommended to u1?

**Comment by bonbon1702** [comment]
um... yes,query both item & user is non-sense.
btw, i customize your engine to mix 2 Algorithm by checking query
for my reason, i deploy 1000 app PIO for 1000 website, i dont want to 1 app, many engine many port....

**Comment by k4hoo** [comment]
Yes. you can use Option[] in query to support different forms of query and then do things differently in Algorithm's predict() function.

You can modify serving to scale the score returned by the "buy" algorithm by a weight and then combine them.
After the score standardization, you get  val standard: Seq[Array[ItemScore]].
let's say your 1st algorithm is using "buy", then you can scale the first Array (which corrsponds to output of 1st algo) of the Seq[] by a weight. (or multiply the second array by smaller  weight). Note that you can also add a parameter class in Serving to control this weight and define it in engine.json

**Comment by bonbon1702** [comment]
Thank you, i made it!

One more question,  i have 2 event now: buy and view

and somtime app dont have buy event, how can i set to ignore buy event?

i get this error when app dont have buy event

```
s"buyEvents in PreparedData cannot be empty." +
        " Please check if DataSource generates TrainingData" +
        " and Preprator generates PreparedData correctly."
```

**Comment by k4hoo** [comment]
Great!  Would you be interested in helping us to add another small section in the multi-aglos doc to describe how to add weight to one algo?
https://github.com/PredictionIO/PredictionIO/blob/livedoc/docs/manual/source/templates/similarproduct/multi-events-multi-algos.html.md.erb

Regarding empty events case, you can remove the require() check. The check() is there for initial checking purpose. If empty events is valid case, then you can remove the check.
then you can add code to check if MllibRatings is empty, don't call the ALS.train(),
https://github.com/PredictionIO/template-scala-parallel-similarproduct/blob/v0.3.2/src/main/scala/ALSAlgorithm.scala#L103
and pass empty Map to the productFeatures in ALSModel instead.
https://github.com/PredictionIO/template-scala-parallel-similarproduct/blob/v0.3.2/src/main/scala/ALSAlgorithm.scala#L113

With empty productFeaturesMap, i believe the predict() would return empty PredictedResult back to Serving. in this case, only PredictedResult from the another algo would be used.

**Comment by bonbon1702** [comment]
Thank you, i will be..
